### ISSUE TITLE
是否可以提供Linux版本？

### ISSUE THREAD

**Issue by ChocoFleece** [0Miles/soku-launcher#2]
是否可以提供Linux版本？

**Comment by 0Miles** [comment]
結論上來說，不會
但我有考慮重新開發一個跨平台的版本

要讓這個專案支援Linux，改用.Net Core是必要的
而這會讓現有的Win使用者需要額外安裝一包.Net runtime
我覺得不太OK
目前這個專案基於WPF與.Net Framework 4.7.2
主要的考量是這個版本的.Net內建於大多數Win10以上的系統，使用者不太需要手動安裝任何相依套件
每多一個安裝步驟對使用者帶來的挫折大到難以想像
(就算安裝簡單到只需要下載一個exe檔放進天則資料夾，仍有人抱怨太過麻煩)

另外就是用Linux打則的人比較少，台灣DC群這邊基本上沒有
有點擔心跨平台版做好卻沒人用(¯―¯٥)

我目前沒有太多跨平台應用的開發經驗
有相關建議的話歡迎加我微信聊聊
ID: length7

**Comment by ChocoFleece** [comment]
> 結論上來說，不會 但我有考慮重新開發一個跨平台的版本
> 
> 要讓這個專案支援Linux，改用.Net Core是必要的 而這會讓現有的Win使用者需要額外安裝一包.Net runtime 我覺得不太OK 目前這個專案基於WPF與.Net Framework 4.7.2 主要的考量是這個版本的.Net內建於大多數Win10以上的系統，使用者不太需要手動安裝任何相依套件 每多一個安裝步驟對使用者帶來的挫折大到難以想像 (就算安裝簡單到只需要下載一個exe檔放進天則資料夾，仍有人抱怨太過麻煩)
> 
> 另外就是用Linux打則的人比較少，台灣DC群這邊基本上沒有 有點擔心跨平台版做好卻沒人用(¯―¯٥)
> 
> 我目前沒有太多跨平台應用的開發經驗 有相關建議的話歡迎加我微信聊聊 ID: length7

那真是有点遗憾了。我这边基本是大部分大陆玩家都可以联系到，在你这个启动器制作之前，大陆使用的简易启动器就是我用python写的，不过功能和易用性比你这个少很多，后面有想过做一个更好的版本，不过中间鸽了。我当时的想法是用flask这种轻量网页内核做一个全平台的软件，因为真的有人的电脑分辨率很鬼畜（640x480 175%缩放），所以最早想到了用网页内核。Linux打则的用户群体确实不大，据我所知目前大陆活跃的用户包括我在内也就只有三到四个人。

关于启动器本身，我也注意到了一些问题，比如直接识别modules文件夹中的dll会导致类似大厅mod中两个无用dll被识别。首次使用的版本号通过强制更新覆盖来确定。这都是我在开发中遇到过的问题。现在我们这边有想过修改更新json文件来用于大陆的普遍用户群体，不过特殊的网络环境没有合适的下载直链也是个问题。还有最让我崩溃的直接导致我鸽了两个问题，有插件更新版本不更新dll，只更新资料档案，这意味着你根本无法更新插件的版本号来控制更新...以及则2对于插件在SWRSTots.ini中的位置甚至有要求这两个问题（什么鬼啊）

关于下载麻烦的问题，大陆这边的天则都是在QQ群中传递的，现在已经内置了许许多多的更新器了...有用C写的wget工具，有我写的启动器，还有直接从服务器copy完整游戏的工具等等。

总之希望你能坚持下去，之前有想过做成一个类似包管理器一样的启动器，不过到最后实在是懒就鸽了。我本人也没有多少开发经验，我的整个启动器都是一边学习一边开发的，有时写着Python很真的很羡慕Csharp的效率和体积...
