### ISSUE TITLE
Game crashes when pressing enter in multiplayer 

### ISSUE THREAD

**Issue by AREYsan** [0Miles/soku-launcher#5]
it usualy gives an blank error window. It says sometimes error is logged in a log file, and also sometimes (rarely) gives an d3d error. when i check it with debug tool, there is an error "creating texture for wtext" ps: i checked my key config and enter is an blank key. not in use of any profile
![touhoubug](https://github.com/user-attachments/assets/b916f57b-fcd9-4482-b31b-cd5ecf4b0358)

**Comment by 0Miles** [comment]
This seems to be an issue related to SokuLobbies mod. 
You can notify the SokuLobbies developer about it here: [https://github.com/PinkySmile/SokuLobbies/issues](https://github.com/PinkySmile/SokuLobbies/issues)
